# These are supported funding model platforms

patreon: # Replace with a single Patreon username
ko_fi: # Replace with a single Ko-fi username
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
